spring:
  application:
    name: patient-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:h2:./data/db;AUTO_SERVER=true
    username: test
    password: test
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql


server:
  port: 4000

